use pizza_sales_project;

# 1.get revenue of a particular order
delimiter $$
create function get_order_revenue(
    p_order_id int
)
returns decimal(10,2)
deterministic
begin
    declare total_revenue decimal(10,2);

    select round(sum(p.price * od.quantity), 2)
    into total_revenue
    from pizzas p
    inner join order_details od
        on p.pizza_id = od.pizza_id
    where od.order_id = p_order_id;

    return total_revenue;
end $$
delimiter ;
select get_order_revenue(1050) as total_bill; -- calling

# 2.get total pizzas in an order
delimiter $$
create function get_total_pizzas(
    p_order_id int
)
returns int
deterministic
begin

    declare total_pizzas int;

    select ifnull(sum(quantity), 0)
    into total_pizzas
    from order_details
    where order_id = p_order_id;

    return total_pizzas;
end $$
delimiter ;
select get_total_pizzas(100);

# 3. order is large or not
delimiter $$

create function is_large_order(
    p_order_id int
)
returns varchar(3)
deterministic
begin

    declare total_revenue decimal(10,2);

    select ifnull(sum(p.price * od.quantity), 0)
    into total_revenue
    from pizzas p
    inner join order_details od
        on p.pizza_id = od.pizza_id
    where od.order_id = p_order_id;

    if total_revenue > 40 then
        return 'yes';
    else
        return 'no';
    end if;
end $$
delimiter ;

# 4. categorize order based on revenue generated by it
delimiter $$
create function order_category(
    p_order_id int
)
returns varchar(10)
deterministic
begin

    declare total_revenue decimal(10,2);

    select ifnull(sum(p.price * od.quantity), 0)
    into total_revenue
    from pizzas p
    inner join order_details od
        on p.pizza_id = od.pizza_id
    where od.order_id = p_order_id;

    if total_revenue < 20 then
        return 'low';

    elseif total_revenue <= 40 then
        return 'medium';

    else
        return 'high';

    end if;

end $$
delimiter ;

# 5. is the given date is weekend or not
delimiter $$

create function is_weekend(
    p_order_date date
)
returns varchar(3)
deterministic
begin
    if dayofweek(p_order_date) in (1, 7) then
        return 'yes';
    else
        return 'no';
    end if;

end $$
delimiter ;

# 6. calculate discount percentage based on order amount
delimiter $$
create function discount_percentage(
    p_bill_amount decimal(10,2)
)
returns int
deterministic
begin
    if p_bill_amount < 20 then
        return 0;
    elseif p_bill_amount <= 40 then
        return 5;
    else
        return 10;
    end if;
end $$
delimiter ;

# 7. calculate loyalty point of customers based on their bill
delimiter $$

create function loyalty_points(
    p_order_id int
)
returns int
deterministic
begin
    declare total_revenue decimal(10,2);

    set total_revenue = order_revenue(p_order_id);

    return floor(total_revenue / 10);

end $$
delimiter ;

# 8. calculate final bill after applying discount
delimiter $$

create function final_bill_after_discount(
    p_order_id int
)
returns decimal(10,2)
deterministic
begin
    declare bill decimal(10,2);
    declare discount int;

    set bill = order_revenue(p_order_id);

    set discount = discount_percentage(bill);

    return round(
        bill - (bill * discount / 100),
        2
    );
end $$
delimiter ;




